export enum Langs {
  RU = 'ru',
  EN = 'en',
}

export const translate = {
  en: {
    header: {
      nav: {
        home: 'Home',
        shop: 'Shop',
        blog: 'Blog',
        club: 'Club',
        contacts: 'Contacts',
      },
      search: {
        search: 'Search',
        error: 'Enter your request',
        inShop: 'in shop',
        inBlog: 'in blog',
      },
      account: {
        account: 'Account',
        admin: 'Admin',
        logout: 'Logout',
        login: 'Log In',
        register: 'Sign Up',
        close: 'Close',
      },
      shopMenu: {
        cart: 'Cart',
        ea: 'ea',
        cost: 'Cost',
        goToCart: 'Place an order',
        close: 'Close',
      },
    },
    footer: {
      policy: 'Confidentiality Policy',
      cookies: 'Use of cookies',
    },
    home: {
      title: 'International community',
      description:
        'Welcome to the EVO community space. Here we are interested in the care of health, beauty and longevity. All users have access to such services as e-shop, blog, social network. Every day we are getting bigger. We`ll be glad to see you in the community, and help you reach your goals.',
    },
    shop: {
      categories: 'Categories',
      sorting: 'Sorting',
      priceDesc: 'price desc',
      priceAsc: 'price asc',
      pop: 'pop',
      new: 'new',
      filter: {
        filtration: 'Filtration',
        price: 'Price',
        from: 'from',
        to: 'to',
        ratings: 'Ratings',
        title: 'Title',
        maker: 'Maker',
        apply: 'Apply',
        reset: 'Reset',
      },
      product: {
        by: 'By',
        quantity: 'Quantity',
        cost: 'Cost',
        add: 'Add to cart',
        characteristics: 'Characteristics',
        manufacturer: 'Manufacturer',
        country: 'Country',
        city: 'City',
        year: 'Year',
        popular: 'Popular in this category',
        reviews: 'Reviews',
        addReview: 'Add',
        noReviews: 'No reviews. Write first!',
        send: 'Send',
        cancel: 'cancel',
        rating: 'Your rating',
        text: 'Text',
        unrated: 'unrated',
        stars: 'stars',
        stars2: 'stars',
        star: 'star',
        choose: 'choose',
        reviewBodyValidate: {
          required_error: 'Enter your review',
          message: 'Enter your review',
        },
        reviewRatingValidate: {
          required_error: 'Select an option',
          message: 'Select an option',
        },
        sendReviewInfo:
          'Your review has been sent to the administrator for review.',
        sendReviewError: 'Something went wrong!',
        description: 'Description',
      },
      cart: {
        cart: 'Cart',
        notification: 'To place an order you need ',
        register: 'to register ',
        login: 'or log in to your account.',
        recipientDetails: 'Recipient details',
        firstName: 'First name',
        middleName: 'Middle name',
        lastName: 'Last name',
        receivingAddress: 'Receiving address',
        country: 'Country',
        city: 'City',
        street: 'Street',
        house: 'House',
        apartment: 'Apartment (if available)',
        postalCode: 'Postal code',
        orderSummery: 'Order Summery',
        totalProducts: 'Total products',
        discount: 'Discount',
        orderAmount: 'Order amount',
        coupon: 'Coupon',
        apply: 'Apply',
        placeAnOrder: 'Place an order',
        required_error: 'Required',
      },
      mobileMenu: {
        menu: 'Menu',
        sort: 'Sort',
        filter: 'Filter',
        compare: 'Compare',
        favorites: 'Favorites',
        cart: 'Cart',
      },
    },
    blog: {
      categories: 'Categories',
      popular: 'Popular',
      post: {
        comments: 'Comments',
        add: 'Add',
      },
    },
    club: {
      categories: 'Categories',
      mayPage: 'My page',
      messenger: 'Messenger',
      groups: 'Groups',
      users: 'Users',
      events: 'Events',
      matching: 'Matching interests',
      noMatching: 'Fill out your profile so we can recommend users to you',
      mobileMenu: {
        myPage: 'My page',
        messenger: 'Messenger',
        groups: 'Groups',
        users: 'Users',
        events: 'Events',
      },
    },
    contacts: {
      title: 'Title',
      body: 'Text',
      titleValidate: 'Enter title',
      bodyValidate: 'Enter text',
      sendEmail: 'Send an email',
      wrong: 'Something went wrong!',
      send: 'Send',
    },
    auth: {
      login: {
        login: 'Log In',
        registration: 'Registration',
        email: 'Email',
        password: 'Password',
        have: 'You dont have an account?',
        send: 'Send',
        emailValidate: {
          required_error: 'Enter your email',
          message: 'Enter your email',
          correct: 'Enter the correct email',
        },
        passwordValidate: {
          required_error: 'Enter password',
          message: 'Enter the correct password',
          correct: 'Enter the correct password',
        },
      },
      register: {
        login: 'Login',
        have: 'Do you have an account?',
        loginValidate: {
          required_error: 'Enter your login',
          messageMin: 'Minimum length 2 characters',
          messageMax: 'Maximum length 32 characters',
        },
        passwordValidate: {
          required_error: 'Enter password',
          messageMin: 'Minimum length 8 characters',
          messageMax: 'Maximum length 32 characters',
        },
      },
    },
    account: {
      mobileMenu: {
        profile: 'Profile',
        orders: 'Orders',
        reviews: 'Reviews',
        comments: 'Comments',
        sections: 'Sections',
      },
      events: {
        events: 'Events',
        noEvents: 'No events',
      },
    },
    admin: {
      nav: {
        title: 'Admin panel',
        dashboard: 'Dashboard',
        products: 'Products',
        reviews: 'Reviews',
        orders: 'Orders',
        articles: 'Articles',
        comments: 'Comments',
        feedback: 'Feedback',
      },
    },
  },
  ru: {
    header: {
      nav: {
        home: 'Главная',
        shop: 'Магазин',
        blog: 'Блог',
        club: 'Клуб',
        contacts: 'Контакты',
      },
      search: {
        search: 'Поиск',
        error: 'Введите запрос',
        inShop: 'в магазине',
        inBlog: 'в блоге',
      },
      account: {
        account: 'Кабинет',
        admin: 'Админка',
        logout: 'Выйти',
        login: 'Войти',
        register: 'Регистрация',
      },
      shopMenu: {
        cart: 'Корзина',
        ea: 'ед.',
        cost: 'Стоимость',
        goToCart: 'Оформить заказ',
        close: 'Закрыть',
      },
    },
    footer: {
      policy: 'Политика конфиденциальности',
      cookies: 'Использование файлов cookie',
    },
    home: {
      title: 'Международное сообщество',
      description:
        'Добро пожаловать в сообщество EVO. Здесь нас интересует забота о здоровье, красоте и долголетии. Все пользователи имеют доступ к таким сервисам, как интернет-магазин, блог, социальная сеть. С каждым днем нас становится больше. Мы будем рады видеть вас в сообществе и помочь вам в достижении ваших целей.',
    },
    shop: {
      categories: 'Категории',
      sorting: 'Сортировка',
      priceDesc: 'убывание цены',
      priceAsc: 'возростание цены',
      pop: 'популярные',
      new: 'новые',
      filter: {
        filtration: 'Фильтрация',
        price: 'Цена',
        from: 'от',
        to: 'до',
        ratings: 'Рейтинг',
        title: 'Заголовок',
        maker: 'Производитель',
        apply: 'Применить',
        reset: 'Сбросить',
      },
      product: {
        by: 'От',
        quantity: 'Количество',
        cost: 'Стоимость',
        add: 'В корзину',
        characteristics: 'Характеристики',
        manufacturer: 'Производитель',
        country: 'Страна',
        city: 'Город',
        year: 'Год',
        popular: 'Популярное в этой категории',
        reviews: 'Отзывы',
        addReview: 'Добавить',
        noReviews: 'Отзывов нет. Напишите первый!',
        send: 'Отправить',
        cancel: 'Отмена',
        rating: 'Ваш рейтинг',
        text: 'Текст',
        unrated: 'без рейтинга',
        stars: 'звёзд',
        stars2: 'звезды',
        star: 'звезда',
        choose: 'выбрать',
        reviewBodyValidate: {
          required_error: 'Введите ваш отзыв',
          message: 'Введите ваш отзыв',
        },
        reviewRatingValidate: {
          required_error: 'Сделайте выбор',
          message: 'Сделайте выбор',
        },
        sendReviewInfo: 'Ваш отзыв отправлен на проверку.',
        sendReviewError: 'Что-то пошло не так!',
        description: 'Описание',
      },
      cart: {
        cart: 'Корзина',
        notification: 'Что бы оформить заказ вам нужно ',
        register: 'зарегистрироваться ',
        login: 'или войти в ваш аккаунт.',
        recipientDetails: 'Данные получателя',
        firstName: 'Имя',
        lastName: 'Фамилия',
        middleName: 'Отчество',
        receivingAddress: 'Адрес получателя',
        country: 'Страна',
        city: 'Город',
        street: 'Улица',
        house: 'Дом',
        apartment: 'Квартира (если имеется)',
        postalCode: 'Почтовый индекс',
        orderSummery: 'О заказе',
        totalProducts: 'Всего товаров',
        discount: 'Скидка',
        orderAmount: 'Сумма заказа',
        coupon: 'Купон',
        apply: 'Применить',
        placeAnOrder: 'Оформить заказ',
        required_error: 'Обязательно для заполнения',
      },
      mobileMenu: {
        menu: 'Меню',
        sort: 'Сорт.',
        filter: 'Фильтр',
        compare: 'Сравн.',
        favorites: 'Избрано',
        cart: 'Корзина',
      },
    },
    blog: {
      categories: 'Категории',
      popular: 'Популярное',
      post: {
        comments: 'Комментарии',
        add: 'Добавить',
      },
    },
    club: {
      categories: 'Категории',
      mayPage: 'Моя страница',
      messenger: 'Мессенджер',
      groups: 'Группы',
      users: 'Пользователи',
      events: 'События',
      matching: 'Совпадение интересов',
      noMatching:
        'Заполните свой профиль, чтобы мы могли рекомендовать вам пользователей',
      mobileMenu: {
        myPage: 'Моя стр.',
        messenger: 'Мессенджер',
        groups: 'Группы',
        users: 'Люди',
        events: 'Страницы',
      },
    },
    contacts: {
      title: 'Заголовок',
      body: 'Текст',
      titleValidate: 'Введите заголовок',
      bodyValidate: 'Введите текст',
      sendEmail: 'Отправить письмо',
      wrong: 'Что-то пошло не так!',
      send: 'Отправить',
    },
    auth: {
      login: {
        login: 'Вход',
        registration: 'Регистрация',
        email: 'Email',
        password: 'Пароль',
        have: 'У вас нет аккаунта?',
        send: 'Отправить',
        emailValidate: {
          required_error: 'Введите ваш email',
          message: 'Введите ваш email',
          correct: 'Введите корректный email',
        },
        passwordValidate: {
          required_error: 'Введите пароль',
          message: 'Введите корректный пароль',
          correct: 'Введите корректный пароль',
        },
      },
      register: {
        login: 'Логин',
        have: 'У вас есть аккаунт?',
        loginValidate: {
          required_error: 'Введите ваш логин',
          messageMin: 'Минимум две буквы',
          messageMax: 'Максимум 32 буквы',
        },
        passwordValidate: {
          required_error: 'Enter password',
          messageMin: 'Минимум 8 символов',
          messageMax: 'Максимум 32 символа',
        },
      },
    },
    account: {
      mobileMenu: {
        profile: 'Профиль',
        orders: 'Заказы',
        reviews: 'Отзывы',
        comments: 'Комментарии',
        sections: 'Разделы',
      },
      events: {
        events: 'События',
        noEvents: 'Нет событий',
      },
    },
    admin: {
      nav: {
        title: 'Админ панель',
        dashboard: 'Дашборд',
        products: 'Товары',
        reviews: 'Отзывы',
        orders: 'Заказы',
        articles: 'Статьи',
        comments: 'Комментарии',
        feedback: 'Фидбек',
      },
    },
  },
}
