import { ReactNode } from 'react'
import type { Metadata } from 'next'
import '../assets/styles/globals.css'
import { Header } from './_elements/Header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
