export { AddToCart } from './AddToCart/AddToCart'
// export { BookMarkButton } from './BookMarkButton/BookMarkButton'
// export { FavoritesButton } from './FavoritesButton/FavoritesButton'
export { Slider } from './Slider/Slider'
export { Popular } from './Popular/Popular'
// export { Reviews } from './Reviews/Reviews'
