name: CD/CD
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
  NEXT_PUBLIC_SAIT_URL: ${{ secrets.NEXT_PUBLIC_SAIT_URL }}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Lint types
        run: npm run lint:types
      - name: Test
        run: npm run test
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    concurrency:
      group: prod
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          # hostname / IP of the server
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{secrets.PROD_SSH_PORT}}
          user: ${{ secrets.PROD_SSH_USERNAME }}
          private_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          host_key: ${{ secrets.PROD_SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; echo 'hi'
