name: CD
on:
  pull_request:
    branches: ['main']
    types: [closed]
env:
  NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
  NEXT_PUBLIC_SAIT_URL: ${{ secrets.NEXT_PUBLIC_SAIT_URL }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  CD:
    runs-on: ubuntu-latest
    concurrency:
      group: main
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          user: ${{ secrets.PROD_SSH_USERNAME }}
          private_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.PROD_SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; ~/deploy-frontend.sh
