export { Actions } from './Actions/Actions'
export { Slider } from './Slider/Slider'
export { Popular } from './Popular/Popular'
export { Reviews } from './Reviews/Reviews'
export { ReviewForm } from './ReviewForm/ReviewForm'
export { Characteristics } from './Characteristics/Characteristics'
export { Description } from './Description/Description'
export { Manufacturer } from './Manufacturer/Manufacturer'
